server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-service?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice
  cloud:
    nacos:
      server-addr: localhost:8848
mybatis:
  type-aliases-package: com.mywork.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#
feign:
  okhttp:
    enabled: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka