server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-service?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: viewservice
  cloud:
    nacos:
      server-addr: localhost:8848

  mvc:
    hiddenmethod:
      filter:
        enable=true
mybatis:
  type-aliases-package: com.mywork.view.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#feign:
#  client:
#    config:
#      default: # default全局的配置
#        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
#  httpclient:
#    enabled: true # 开启feign对HttpClient的支持
#    max-connections: 200 # 最大的连接数
#    max-connections-per-route: 50 # 每个路径的最大连接数
#feign:
#  okhttp:
#    enabled: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka